// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANI2UsNn7r8wIo3XCPWegzGxpuV5pQugw',
    appId: '1:637391228731:web:18abd21545ed66b96d311e',
    messagingSenderId: '637391228731',
    projectId: 'one-go-ecommerce',
    authDomain: 'one-go-ecommerce.firebaseapp.com',
    storageBucket: 'one-go-ecommerce.firebasestorage.app',
    measurementId: 'G-H7PWE38SKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqQoFQOzwWnOgEeiE-vGrpZvoVkNUdb7Q',
    appId: '1:637391228731:android:d8ea609e657747d46d311e',
    messagingSenderId: '637391228731',
    projectId: 'one-go-ecommerce',
    storageBucket: 'one-go-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvrWf_3NnLu4kSQ5MrPTQOHUT-16A7gX0',
    appId: '1:637391228731:ios:5ab757b028ded3906d311e',
    messagingSenderId: '637391228731',
    projectId: 'one-go-ecommerce',
    storageBucket: 'one-go-ecommerce.firebasestorage.app',
    iosBundleId: 'com.onego.mobileapp.customer',
  );

}